server:
    context-path: /
    port: 8088
spring:
  datasource:
    name: test
    url: jdbc:mysql://122.51.229.137:3216/springcloud?characterEncoding=utf8
    username: root
    password: Jiayoulr@597.
#   使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
#  jpa配置
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  application:
    name: mocroservice-provider-user #指定服务的名称,建议使用小写
logging:
  level: info


eureka:
  client:
    service-url:
    #配置注册中心地址
          defaultZone: http://admin:admin@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}}


