server:
  port: 8761
eureka:
  client:
    healthcheck:
          enabled: true
#表示是否将自己注册到Eureka Server上，默认为true
    register-with-eureka: false
#表示是否从Eureka Server上获取注册信息，默认为true
    fetch-registry: false
    service-url:
          defaultZone: http://user:password@localhost:8761/eureka
#注册中心配置登录验证
security:
  basic:
    enabled: true
  user:
    name: admin #用户名
    password: admin #密码
